# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-16 12:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rememberTheCheese', '0004_auto_20160816_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 19, 12, 47, 43, 644033, tzinfo=utc), verbose_name='deadline'),
        ),
        migrations.AlterField(
            model_name='lista',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 31, 12, 47, 43, 361731, tzinfo=utc), verbose_name='deadline'),
        ),
    ]
