# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-21 03:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rememberTheCheese', '0008_auto_20160821_0249'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('deadline', models.DateTimeField(default=datetime.datetime(2016, 8, 24, 3, 9, 31, 834651, tzinfo=utc), verbose_name='deadline')),
                ('finished', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('date_create', models.DateTimeField(default=datetime.datetime(2016, 8, 21, 3, 9, 31, 555099, tzinfo=utc), verbose_name='date created')),
                ('deadline', models.DateTimeField(default=datetime.datetime(2016, 9, 5, 3, 9, 31, 555170, tzinfo=utc), verbose_name='deadline')),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='lista',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Lista',
        ),
        migrations.AddField(
            model_name='subtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rememberTheCheese.Task'),
        ),
    ]
