# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-21 12:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rememberTheCheese', '0009_auto_20160821_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='finished',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 24, 12, 14, 15, 596727, tzinfo=utc), verbose_name='deadline'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 21, 12, 14, 15, 320165, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 5, 12, 14, 15, 320240, tzinfo=utc), verbose_name='deadline'),
        ),
    ]
