# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-25 14:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rememberTheCheese', '0010_auto_20160821_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 28, 14, 22, 23, 685416, tzinfo=utc), verbose_name='deadline'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 25, 14, 22, 23, 413198, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 28, 14, 22, 23, 413272, tzinfo=utc), verbose_name='deadline'),
        ),
    ]
