# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-05 18:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rememberTheCheese', '0015_auto_20160828_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 8, 18, 14, 39, 94699, tzinfo=utc), verbose_name='deadline'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 8, 18, 14, 39, 66710, tzinfo=utc), verbose_name='deadline'),
        ),
    ]
