# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-10 21:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rememberTheCheese', '0017_auto_20160910_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='started',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 13, 21, 12, 24, 886494, tzinfo=utc), verbose_name='deadline'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 13, 21, 12, 24, 884845, tzinfo=utc), verbose_name='deadline'),
        ),
    ]
