# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-10 22:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rememberTheCheese', '0024_auto_20160910_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='observation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 13, 22, 41, 34, 43114, tzinfo=utc), verbose_name='deadline'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 13, 22, 41, 34, 41513, tzinfo=utc), verbose_name='deadline'),
        ),
    ]
