# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-16 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('deadline', models.DateTimeField(verbose_name='deadline')),
                ('finished', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('date_create', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='lista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rememberTheCheese.Lista'),
        ),
    ]
