# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-16 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rememberTheCheese', '0002_lista_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='deadline'),
        ),
    ]
