# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-16 12:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rememberTheCheese', '0003_auto_20160816_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 19, 12, 43, 57, 108277, tzinfo=utc), verbose_name='deadline'),
        ),
        migrations.AlterField(
            model_name='lista',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 19, 12, 43, 56, 828139, tzinfo=utc), verbose_name='deadline'),
        ),
    ]
