# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-18 18:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rememberTheCheese', '0006_auto_20160818_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 21, 18, 56, 2, 329286, tzinfo=utc), verbose_name='deadline'),
        ),
        migrations.AlterField(
            model_name='lista',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 2, 18, 56, 2, 51486, tzinfo=utc), verbose_name='deadline'),
        ),
    ]
