# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-21 02:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rememberTheCheese', '0007_auto_20160818_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 24, 2, 49, 30, 563314, tzinfo=utc), verbose_name='deadline'),
        ),
        migrations.AlterField(
            model_name='lista',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 21, 2, 49, 30, 270956, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='lista',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 5, 2, 49, 30, 271029, tzinfo=utc), verbose_name='deadline'),
        ),
    ]
