# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-25 14:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rememberTheCheese', '0011_auto_20160825_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 28, 14, 27, 45, 934416, tzinfo=utc), verbose_name='deadline'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 25, 14, 27, 45, 663944, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 28, 14, 27, 45, 664021, tzinfo=utc), verbose_name='deadline'),
        ),
    ]
