# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-25 14:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rememberTheCheese', '0012_auto_20160825_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date_create',
        ),
        migrations.AddField(
            model_name='subtask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 25, 14, 40, 44, 675216, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subtask',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 8, 25, 14, 40, 54, 589058, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 25, 14, 41, 12, 908668, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 8, 25, 14, 41, 46, 841359, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subtask',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 28, 14, 40, 18, 633475, tzinfo=utc), verbose_name='deadline'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 28, 14, 40, 18, 347422, tzinfo=utc), verbose_name='deadline'),
        ),
    ]
