# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-28 23:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rememberTheCheese', '0014_auto_20160826_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 31, 23, 35, 49, 874765, tzinfo=utc), verbose_name='deadline'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 31, 23, 35, 49, 605022, tzinfo=utc), verbose_name='deadline'),
        ),
    ]
